### ISSUE TITLE
Reachablity from external peers other than target servers

### ISSUE THREAD

**Issue by zaheduzzaman** [mirjak/draft-kuehlewind-masque-connect-ip#8]
It is not clear how Tunnel mode allows forwarding of incoming IP packets to the client while flow forwarding mode does not do that. The IP-Connect method is always client initiated with a target server to the proxy. Then the proxy creates connection towards the target server. Hence it is always going to work for know target server. Why and how the tunnel mode will allow forwarding of IP packets from unknown target server to the client?

**Comment by mirjak** [comment]
With tunnel mode you tell the proxy please forward everything address to this IP Address for IP address over this tunnel; there is no specific target server provided to the proxy. In flow forwarding mode both the source and destination have to match. So with tunnel mode the client also has to open a tunnel but then all incoming traffic is accepted.

**Comment by zaheduzzaman** [comment]
- This operation mood then need to be written clearly in the tunnel mode section.
- and I also wonder why would the proxy allow traffic coming from any IP address to the client in tunneling mode.

**Comment by gloinul** [comment]
@zaheduzzaman in my view a default IP tunnel will forward all traffic with a destination IP the same as the IP given to the client (its IP point of presence) to that client. Yes, it can be restricted, however, then you are into the network to network routing rules negotiation. With Tunnel mode all is forward, with flow forwarding mode you have a point to point flow only for one ULP, with possibility to down select this even further. I think these two are the correct starting points. All else is further extensions. Client side routing rules are outside of this specification, so what gets sent over the tunnel is another question.
